### ISSUE TITLE
Use ROLLBAR_ENV if set

### ISSUE THREAD

**Issue by AxelTheGerman** [iloveitaly/dokku-rollbar#2]
Rollbar allows overwriting the applications default environment variable, such as `RAILS_ENV`, with `ROLLBAR_ENV`

Should check for `ROLLBAR_ENV` first, then fall back to rack, rails and `production`
```
ENVIRONMENT=$(dokku config:get "$APP" RACK_ENV || dokku config:get "$APP" RAILS_ENV || echo 'production')
```

**Comment by iloveitaly** [comment]
@AxelTheGerman Great idea! Want to create a PR?

**Comment by AxelTheGerman** [comment]
Definitely! I'm on it :)
