### ISSUE TITLE
Reporting git hash from previous deploy

### ISSUE THREAD

**Issue by AxelTheGerman** [iloveitaly/dokku-rollbar#4]
I noticed that the commit hash is always off by one deploy, due to how the post-deploy hook works. Other plugins ran into the same problem, see Flink/dokku-airbrake-deploy#1

Two ways to fix this:
- add a `receive-app` hook similar to https://github.com/Flink/dokku-airbrake-deploy/commit/721d95e203260d452ee75237c991d39a959fd4b1
- require [dokku-community/dokku-git-rev](https://github.com/dokku-community/dokku-git-rev) plugin to be installed and use `GIT_REV` set by that plugin

Such a shame this simple task requires another hook

**Comment by AxelTheGerman** [comment]
`dokku-git-rev` is listed under [plugins implementing new dokku functionality](http://dokku.viewdocs.io/dokku/community/plugins/#plugins-implementing-new-dokku-functionality), so it might make sense to just rely on that and require it to be manually installed for now?

**Comment by iloveitaly** [comment]
> so it might make sense to just rely on that and require it to be manually installed for now?

I like this approach. Let's just make sure to make it an optional requirement—I don't want to create dependencies for such a simple plugin.

**Comment by AxelTheGerman** [comment]
Great, I can make a PR for it.
I looked a bit more into the git-rev plugin and it get were open to add it 
to core dokku as soon as it's simply rewritten in go. Might work on a PR 
for that too, so definitely the way to go.

I like the fallback. Will make sure to echo a message that informs the user 
about this issue
