### ISSUE TITLE
Update README regarding GIT_REV

### ISSUE THREAD

**Issue by fgblomqvist** [iloveitaly/dokku-rollbar#6]
GIT_REV is now set by the current Dokku version, no need for the mentioned plugin.
I would submit a PR but I can't figure out which exact version of Dokku supports this. It seems like 0.12.0 or newer is sufficient.

**Comment by fgblomqvist** [comment]
Actually, this is confusing...this plugin complains about GIT_REV not being set, even though it is (if you check dokku config).

**Comment by sman591** [comment]
The docs confirm this being introduced in 0.12.0: http://dokku.viewdocs.io/dokku/deployment/methods/git/#configuring-the-git_rev-environment-variable

**Comment by iloveitaly** [comment]
@fgblomqvist feel free to submit a PR for this! I'm not actively using this anymore so I can't remember the specifics.

**Comment by sman591** [comment]
@fgblomqvist I just tried removing the `dokku-git-rev` plugin and see the same fallback error message. Is it possible that Dokku doesn't make this GIT_REV variable available at the `post-deploy` stage?

The variable gets set by during the Git build: https://github.com/dokku/dokku/blob/eaed0b78cfac09a62caf244f1a97cdc02c3bb386/plugins/git/functions#L164

**Comment by fgblomqvist** [comment]
@sman591 Interesting. Unfortunately I can't wrap my head around the dokku code and the deployment process. It seems to me like the git-build step happens before deployment, and clearly the var is available after deployment.

Looking at the code for this plugin, it uses `dokku config:get` to get the environment and token, but not for the git_rev. Doesn't make any sense to me. Either the plugin operates in the container and can access the env vars directly (like it tries with the GIT_REV) or it operates outside of the container and has to use dokku config (like it does with the rollbar envs).

**Comment by sman591** [comment]
@fgblomqvist Just tested this by retrieving GIT_REV in `post-deploy` via `dokku config:get $APP GIT_REV` and all worked out. My guess is $GIT_REV was made available by the `dokku-git-rev` plugin, whereas the native Dokku integration introduced in 0.12.0 doesn't directly expose these environment variables. Submitting a PR.

**Comment by fgblomqvist** [comment]
Awesome, looks good. Hopefully it can be merged asap.
